# Generated by Django 4.2.4 on 2023-08-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='admin', max_length=256),
            preserve_default=False,
        ),
    ]
